/*package entity;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Data;

@Document(collection = "status")
@Data
public class Status {
    public enum StatusType {
        IMAGE, VIDEO, TEXT
    }

    @Id
    private String id;
    private String userId;
    private StatusType type;
    private String contentUrl;
    private String caption;
    private LocalDateTime createdAt;
    private LocalDateTime expiresAt; // Status disappears after 24 hours
    private int viewCount;
    private Set<String> viewedBy = new HashSet<>();
    
    // New: Transient fields for username and profile photo (populated dynamically)
    @Transient
    private String username;
    @Transient
    private String profilePhotoUrl;
    
    // Getters and setters (Lombok handles most, but explicit for transients)
    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    public String getProfilePhotoUrl() {
        return profilePhotoUrl;
    }
    public void setProfilePhotoUrl(String profilePhotoUrl) {
        this.profilePhotoUrl = profilePhotoUrl;
    }
    
    // Existing getters/setters (auto-generated by Lombok)
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }
    public String getUserId() {
        return userId;
    }
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public StatusType getType() {
        return type;
    }
    public void setType(StatusType type) {
        this.type = type;
    }
    public String getContentUrl() {
        return contentUrl;
    }
    public void setContentUrl(String contentUrl) {
        this.contentUrl = contentUrl;
    }
    public String getCaption() {
        return caption;
    }
    public void setCaption(String caption) {
        this.caption = caption;
    }
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
    public LocalDateTime getExpiresAt() {
        return expiresAt;
    }
    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }
    public int getViewCount() {
        return viewCount;
    }
    public void setViewCount(int viewCount) {
        this.viewCount = viewCount;
    }
    public Set<String> getViewedBy() {
        return viewedBy;
    }
    public void setViewedBy(Set<String> viewedBy) {
        this.viewedBy = viewedBy;
    }
}*/

package entity;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Data;

@Document(collection = "status")
@Data
public class Status {
    public enum StatusType {
        IMAGE, VIDEO, TEXT
    }

    @Id
    private String id;
    private String userId;
    private StatusType type;
    private String contentUrl;
    private String caption;
    private LocalDateTime createdAt;
    private LocalDateTime expiresAt; // Status disappears after 24 hours
    private int viewCount;
    private Set<String> viewedBy = new HashSet<>();
    
    // New: Transient fields for username and profile photo (populated dynamically)
    @Transient
    private String username;
    @Transient
    private String profilePhotoUrl;
    
    // Getters and setters (Lombok handles most, but explicit for transients)
    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    public String getProfilePhotoUrl() {
        return profilePhotoUrl;
    }
    public void setProfilePhotoUrl(String profilePhotoUrl) {
        this.profilePhotoUrl = profilePhotoUrl;
    }
    
    // Existing getters/setters (auto-generated by Lombok)
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }
    public String getUserId() {
        return userId;
    }
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public StatusType getType() {
        return type;
    }
    public void setType(StatusType type) {
        this.type = type;
    }
    public String getContentUrl() {
        return contentUrl;
    }
    public void setContentUrl(String contentUrl) {
        this.contentUrl = contentUrl;
    }
    public String getCaption() {
        return caption;
    }
    public void setCaption(String caption) {
        this.caption = caption;
    }
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
    public LocalDateTime getExpiresAt() {
        return expiresAt;
    }
    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }
    public int getViewCount() {
        return viewCount;
    }
    public void setViewCount(int viewCount) {
        this.viewCount = viewCount;
    }
    public Set<String> getViewedBy() {
        return viewedBy;
    }
    public void setViewedBy(Set<String> viewedBy) {
        this.viewedBy = viewedBy;
    }
}